set SERVEROUTPUT ON

DECLARE

V_EVENT VARCHAR(15);

BEGIN

-- Usar essa concatenação para usar os '
V_EVENT := q'!Father's day!';

DBMS_OUTPUT.PUT_LINE('3rd Sunday in june is : ' || V_EVENT);

END;
/

-- TIPOS DE VARIAVEIS
-- ESCALAR = SÃO TODOS OS TIPOS DE DADOS QUE SAO PRIMITIVOS
-- COMPOSTO = VETOR / TABELA

--CHAR FAZ ARMAZENAMENTO DE DADOS FIXO , MESMO QUE VC N TENHA ARMAZENADO UM VALOR MENOR DE USO
--VARCHAR20 - ARMAZENA A QNTD DE VALOR NECESSARIA
--NUMBER(8,2) VOCÊ TEM OITO BYTES E DESSES 8 BYTES ESTOU SOLICITANDO 2 PARA FAZER O ARMAZENAMENTO DO VALOR *99999999
--BINARY INTEGER , UTILIZADO-SE PARA VETOR
--BOOLEAN PODE SER ACEITAR TRES VALORES , NULL, FALSE , TRUE E VAI ACEITAR OS VALORES PADROES Q SOLICITARÁ NULO 
--BINARY_FLOAT = VALORES BINARIOS SO QUE COM TAMANHO FLOAD E DOUBLE


-- DATE  ARMAZENA FRAÇÕES DE TEMPO ATE 10 A -3 SEGUNDOS
-- TIMESTAMP -  SÓ ARMAZENA VALORES DE MILI SEGUNDOS , FRAÇÕES DE TEMPO ATE 10 A -12 SEGUNDOS
-- TIME ZONE - ARMAZENA FUSO HORARIO , ELE ARMAZENA OS HORARIO ORDENADOS APARTIR DO LOCAL DA CONSULTA
-- INTERVAL YEAR TO MONTH - ARMAZENA O TEMPO DE GARANTIA
-- INTERVAL DAY TO SECOND -  


DESC dept

DECLARE

V_DNAME DEPT.DNAME%TYPE;

BEGIN

SELECT DNAME 
INTO V_DNAME 
FROM DEPT 
WHERE DEPTNO = 10;

END;

/

-- =============================================================================
DECLARE

V_BOL BOOLEAN;

BEGIN

V_BOL := ( 1 = 1);

END;


/


-- BIND - SERVEM PARA VOCÊ LIGAR UMA APLICAÇÕES COM OUTRAS
-- POSSO TRABALHAR COM A SAIDA DE UM BLOCO PL/SQL PARA O JAVA OU PARA UM BLOCO DE PL/SQL

VARIABLE B_RESULT NUMBER

BEGIN

SELECT (SALARY*12) + NVL(COMMISSION_PCT,0) INTO :B_RESULT 
                    FROM EMPLOYEES WHERE employee_id = 144;

END;

print B_RESULT;

