
SELECT * FROM T_SPV_CLIENTE;

--ATIVANDO A INTERAÇÃO DO SQL
SET SERVEROUTPUT ON; 

DECLARE 
                  -- AO INVEZ DE COLOCAR O TIPO DE DADO , VC POEM O NOME DA TABELA E O DA COLUNA
                  -- NA DECLARAÇÃO DE VARIAVEL
                  
V_NM_FUNCIONARIO  T_SPV_CLIENTE.NM_CLIENTE%Type;

BEGIN 

-- ARMAZENANDO O NOME MARIA DENTRO DA VARIAVEL V_NM_FUNCIONARIO
SELECT NM_CLIENTE INTO V_NM_FUNCIONARIO FROM T_SPV_CLIENTE 
    WHERE CD_CLIENTE = 1;
    
    IF V_NM_FUNCIONARIO !=  'MARIA DAS DORES' THEN --FAÇA
        DBMS_OUTPUT.PUT_LINE(V_NM_FUNCIONARIO);
        ELSE
        DBMS_OUTPUT.PUT_LINE('OK');
        END IF;
        END;