-- 1

SET SERVEROUTPUT ON

DECLARE

V_NAME EMP.ENAME%TYPE;
V_SAL EMP.SAL%TYPE;

BEGIN

SELECT ENAME , SAL INTO V_NAME , V_SAL FROM EMP WHERE SAL = 5000;

DBMS_OUTPUT.put_line('NOME : ' || V_NAME || 'SALARIO : ' || V_SAL);

END;


/


DECLARE

V_NAME EMP.ENAME%TYPE;
V_HIREDATE EMP.HIREDATE%TYPE;
V_CODIGO EMP.DEPTNO%TYPE;


BEGIN

SELECT ENAME , DEPTNO , HIREDATE   
INTO V_NAME , V_CODIGO , V_HIREDATE  
FROM EMP WHERE SAL = 5000;

DBMS_OUTPUT.put_line('NOME : ' || V_NAME  || 'DATA :' || TO_CHAR(V_HIREDATE,'DD/MM/YYYY') ||  'CODIGO : ' || V_CODIGO);

END;


/


DECLARE

V_NAME EMP.ENAME%TYPE;
V_SAL EMP.SAL%TYPE;
V_DATA EMP.HIREDATE%TYPE;
V_MENOR_SAL NUMBER(8,2);

BEGIN

SELECT
ENAME ,
SAL,
HIREDATE
INTO V_NAME , V_SAL , V_DATA
FROM EMP 
WHERE SAL =(SELECT MIN(sal) FROM EMP); -- ONDE SALARIO SEJA IGUAL AO MENOR DA MINHA TABELA

DBMS_OUTPUT.put_line('MENOR SALARIO' || TO_CHAR(V_SAL,'L9G999D00') || 
                     'NAME : ' || V_NAME || 
                     'DATA : ' || TO_CHAR(V_DATA,'DD/MM/YYYY'));


END;

/

DECLARE

V_NAME EMP.ENAME%TYPE;
V_SAL EMP.SAL%TYPE;
V_DATA EMP.HIREDATE%TYPE;

BEGIN


SELECT ENAME , SAL , HIREDATE INTO 
V_NAME , V_SAL , V_DATA 
FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);

SELECT ENAME , SAL 
INTO 

DBMS_OUTPUT.put_line('MAIOR SALARIO ' || TO_CHAR(V_SAL,'L9G999D00') || ' NOME : ' || V_NAME );
DBMS_OUTPUT.put_line('MENOR SALARIO ' || TO_CHAR(V_SAL,'L9G999D00') || ' NOME : ' || V_NAME );

END;


SELECT * FROM EMP;